name: Nifty 50 Web Analysis

on:
  schedule:
    # Run every morning at 6:30 AM IST (1:00 AM UTC)
    - cron: '0 1 * * 1-5'  # Weekdays only
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths: 
      - 'main_web.py'
      - 'generate_html.py'
      - '.github/workflows/nifty-web-analysis.yml'

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  nifty-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Nifty 50 Technical Analysis
      run: |
        python main_web.py
        python generate_html.py

    - name: Verify generated files
      run: |
        ls -la
        echo "=== Checking if index.html exists ==="
        if [ -f "index.html" ]; then
          echo "✅ index.html generated successfully"
          head -20 index.html
        else
          echo "❌ index.html not found"
          exit 1
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
    enablement: true  # Add this line
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  # Optional: Send notification on failure
  notify-failure:
    needs: nifty-analysis
    runs-on: ubuntu-latest
    if: failure()

    steps:
    - name: Create Issue on Failure
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Nifty 50 Analysis Workflow Failed',
            body: `The automated Nifty 50 analysis workflow failed on ${new Date().toISOString()}.

            Please check the [workflow logs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions) for details.

            This issue was created automatically.`,
            labels: ['bug', 'automation']
          });
